### ISSUE TITLE
VPN直连，导致 Fiddler 和 Charles 抓包工具无法正常进行抓包解决方案

### ISSUE THREAD

**Issue by MayOMengxuhui** [mopduan/team#13]
| <img src="https://i.loli.net/2017/11/25/5a1986f6af64f.png" width = "50%" height = "50%" alt="图片名称" align=center /> | <img src="https://i.loli.net/2017/11/25/5a1987c26bedd.png" width = "50%" height = "50%" alt="图片名称" align=center /> |
| ---------------------------------------- |--------------------------------------------------|

##### 解决方案，步骤如下：

- 使用 `Chrome`下载并安装 `proxy-switchyomega`插件：
https://chrome.google.com/webstore/detail/proxy-switchyomega/padekgcemlokbadohgkifijomclgjgif?utm_source=chrome-ntp-icon

- 在插件设置界面新建一个情景模式，相关设置如下：
<div text-align="center">
<img src="https://i.loli.net/2017/11/25/5a1988f80118f.jpg" width = "100%" height = "100%" alt="图片名称" align=center />
</div>

- 打开Charles，取消勾选macOSProxy：
<div text-align="center">
<img src="https://i.loli.net/2017/11/25/5a1988f7cf6c3.jpg" width = "100%" height = "100%" alt="图片名称" align=center />
</div>

- 在开发调试页面时，切换到VPNProxy模式即可
<div text-align="center">
<img src="https://i.loli.net/2017/11/25/5a1988f8210db.jpg" width = "100%" height = "100%" alt="图片名称" align=center />
</div>

- 正常使用Charles来抓包，如下图：
<div text-align="center">
<img src="https://i.loli.net/2017/11/25/5a1988f7f4232.jpg" width = "100%" height = "100%" alt="图片名称" align=center />
</div>

**Comment by MayOMengxuhui** [comment]
确实遇到了这个问题 今晚已经解决 按照这个教程

**Comment by ClausClaus** [comment]
你好！我使用Charles4.2.5版本下载后不勾选mac Proxy，浏览器也设置了VPNProxy，但什么都没有抓到，请问你现在还是正常使用中吗？能提供下版本号吗？谢谢！！！

**Comment by hzj-edu-nju** [comment]
工作原理是怎样的

**Comment by Jackie-CJ** [comment]
请问下手机必须要翻墙，然后怎么用Charles抓包呢

**Comment by Ynight919** [comment]
> 请问下手机必须要翻墙，然后怎么用Charles抓包呢

请问有什么好的解决方法吗？

**Comment by Miscf** [comment]
> 请问下手机必须要翻墙，然后怎么用Charles抓包呢

老哥解决了吗？

**Comment by yeyee** [comment]
> 请问下手机必须要翻墙，然后怎么用Charles抓包呢

同问，有解决办法吗

**Comment by kurisunoob** [comment]
> 请问下手机必须要翻墙，然后怎么用Charles抓包呢

老哥 解决了吗

**Comment by kurisunoob** [comment]
> 请问下手机必须要翻墙，然后怎么用Charles抓包呢

老哥 解决了吗

**Comment by kurisunoob** [comment]
> 请问下手机必须要翻墙，然后怎么用Charles抓包呢

老哥 解决了吗

**Comment by kurisunoob** [comment]
> 请问下手机必须要翻墙，然后怎么用Charles抓包呢

老哥 解决了吗

**Comment by omitao** [comment]
proxyman怎么解决

**Comment by ghost** [comment]
> 请问下手机必须要翻墙，然后怎么用Charles抓包呢

二级代理
